from tkinter import *
from Pruebas_Funciones import *

ventana = Tk()
ventana.title("Ventana")
marco = Frame(ventana)

menu = Menu(ventana)
menu.add_command(label="Vista 1", command=lambda: vista_1())
menu.add_command(label="Vista 2", command=lambda: vista_2())
ventana.config(menu=menu, width=100)
'''
vista1 = Menu(menu)
vista1.add_command(label="Vista 1", command=lambda: vista_1())

vista2 = Menu(menu)
vista2.add_command(label="Vista 2", command=lambda: vista_2())

menu.add_cascade(label="Vista 1", menu=vista1)
menu.add_cascade(label="Vista 2", menu=vista2)
'''

url = Obtener_direcciónes()


def destructor():
    e1.destroy()
    e2.destroy()
    e3.destroy()
    e4.destroy()
    e5.destroy()
    e6.destroy()
    e7.destroy()
    e8.destroy()
    e9.destroy()
    e10.destroy()
    marco.destroy()


def vista_2():
    global marco
    marco.destroy()
    marco = Frame(ventana)
    bb1 = Button(marco, text="establecer enlace nº1", command=lambda: pulsar(b1, e1, d1.get()), padx=10, pady=0)
    bb1.grid(row=1, column=3)
    bb2 = Button(marco, text="establecer enlace nº2", command=lambda: pulsar(b2, e2, d2.get()), padx=10, pady=0)
    bb2.grid(row=2, column=3)
    bb3 = Button(marco, text="establecer enlace nº3", command=lambda: pulsar(b3, e3, d3.get()), padx=10, pady=0)
    bb3.grid(row=3, column=3)
    bb4 = Button(marco, text="establecer enlace nº4", command=lambda: pulsar(b4, e4, d4.get()), padx=10, pady=0)
    bb4.grid(row=4, column=3)
    bb5 = Button(marco, text="establecer enlace nº5", command=lambda: pulsar(b5, e5, d5.get()), padx=10, pady=0)
    bb5.grid(row=5, column=3)
    bb6 = Button(marco, text="establecer enlace nº6", command=lambda: pulsar(b6, e6, d6.get()), padx=10, pady=0)
    bb6.grid(row=6, column=3)
    bb7 = Button(marco, text="establecer enlace nº7", command=lambda: pulsar(b7, e7, d7.get()), padx=10, pady=0)
    bb7.grid(row=7, column=3)
    bb8 = Button(marco, text="establecer enlace nº8", command=lambda: pulsar(b8, e8, d8.get()), padx=10, pady=0)
    bb8.grid(row=8, column=3)
    bb9 = Button(marco, text="establecer enlace nº9", command=lambda: pulsar(b9, e9, d9.get()), padx=10, pady=0)
    bb9.grid(row=9, column=3)
    bb10 = Button(marco, text="establecer enlace nº10", command=lambda: pulsar(b10, e10, d10.get()), padx=10, pady=0)
    bb10.grid(row=10, column=3)
    marco.pack()


def vista_1():
    global marco
    marco.destroy()
    marco = Frame(ventana)
    ee1 = Label(marco, text="Video 1", fg="blue", cursor="hand2", padx=10, pady=20)
    ee1.bind("<Button-1>", lambda e: llamar(url[0]))
    ee1.grid(row=1, column=2)
    ee2 = Label(marco, text="Video 2", fg="blue", cursor="hand2", padx=10, pady=20)
    ee2.bind("<Button-1>", lambda e: llamar(url[1]))
    ee2.grid(row=2, column=2)
    ee3 = Label(marco, text="Video 3", fg="blue", cursor="hand2", padx=10, pady=20)
    ee3.bind("<Button-1>", lambda e: llamar(url[2]))
    ee3.grid(row=3, column=2)
    ee4 = Label(marco, text="Video 4", fg="blue", cursor="hand2", padx=10, pady=20)
    ee4.bind("<Button-1>", lambda e: llamar(url[3]))
    ee4.grid(row=4, column=2)
    ee5 = Label(marco, text="Video 5", fg="blue", cursor="hand2", padx=10, pady=20)
    ee5.bind("<Button-1>", lambda e: llamar(url[4]))
    ee5.grid(row=5, column=2)
    ee6 = Label(marco, text="Video 6", fg="blue", cursor="hand2", padx=10, pady=20)
    ee6.bind("<Button-1>", lambda e: llamar(url[5]))
    ee6.grid(row=6, column=2)
    ee7 = Label(marco, text="Video 7", fg="blue", cursor="hand2", padx=10, pady=20)
    ee7.bind("<Button-1>", lambda e: llamar(url[6]))
    ee7.grid(row=7, column=2)
    ee8 = Label(marco, text="Video 8", fg="blue", cursor="hand2", padx=10, pady=20)
    ee8.bind("<Button-1>", lambda e: llamar(url[7]))
    ee8.grid(row=8, column=2)
    ee9 = Label(marco, text="Artículo H.", fg="blue", cursor="hand2", padx=10, pady=20)
    ee9.bind("<Button-1>", lambda e: llamar(url[8]))
    ee9.grid(row=9, column=2)
    ee10 = Label(marco, text="Artículo C.", fg="blue", cursor="hand2", padx=10, pady=20)
    ee10.bind("<Button-1>", lambda e: llamar(url[9]))
    ee10.grid(row=10, column=2)

    dd1 = Entry(marco)
    dd1.grid(row=1, column=1, padx=10, pady=20)
    dd2 = Entry(marco)
    dd2.grid(row=2, column=1, padx=10, pady=20)
    dd3 = Entry(marco)
    dd3.grid(row=3, column=1, padx=10, pady=20)
    dd4 = Entry(marco)
    dd4.grid(row=4, column=1, padx=10, pady=20)
    dd5 = Entry(marco)
    dd5.grid(row=5, column=1, padx=10, pady=20)
    dd6 = Entry(marco)
    dd6.grid(row=6, column=1, padx=10, pady=20)
    dd7 = Entry(marco)
    dd7.grid(row=7, column=1, padx=10, pady=20)
    dd8 = Entry(marco)
    dd8.grid(row=8, column=1, padx=10, pady=20)
    dd9 = Entry(marco)
    dd9.grid(row=9, column=1, padx=10, pady=20)
    dd10 = Entry(marco)
    dd10.grid(row=10, column=1, padx=10, pady=20)

    bb1 = Button(marco, text="establecer enlace nº1", command=lambda: pulsar(b1, e1, d1.get()), padx=10, pady=0)
    bb1.grid(row=1, column=3)
    bb2 = Button(marco, text="establecer enlace nº2", command=lambda: pulsar(b2, e2, d2.get()), padx=10, pady=0)
    bb2.grid(row=2, column=3)
    bb3 = Button(marco, text="establecer enlace nº3", command=lambda: pulsar(b3, e3, d3.get()), padx=10, pady=0)
    bb3.grid(row=3, column=3)
    bb4 = Button(marco, text="establecer enlace nº4", command=lambda: pulsar(b4, e4, d4.get()), padx=10, pady=0)
    bb4.grid(row=4, column=3)
    bb5 = Button(marco, text="establecer enlace nº5", command=lambda: pulsar(b5, e5, d5.get()), padx=10, pady=0)
    bb5.grid(row=5, column=3)
    bb6 = Button(marco, text="establecer enlace nº6", command=lambda: pulsar(b6, e6, d6.get()), padx=10, pady=0)
    bb6.grid(row=6, column=3)
    bb7 = Button(marco, text="establecer enlace nº7", command=lambda: pulsar(b7, e7, d7.get()), padx=10, pady=0)
    bb7.grid(row=7, column=3)
    bb8 = Button(marco, text="establecer enlace nº8", command=lambda: pulsar(b8, e8, d8.get()), padx=10, pady=0)
    bb8.grid(row=8, column=3)
    bb9 = Button(marco, text="establecer enlace nº9", command=lambda: pulsar(b9, e9, d9.get()), padx=10, pady=0)
    bb9.grid(row=9, column=3)
    bb10 = Button(marco, text="establecer enlace nº10", command=lambda: pulsar(b10, e10, d10.get()), padx=10, pady=0)
    bb10.grid(row=10, column=3)
    marco.pack()


e1 = Label(marco, text="Video 1", fg="blue", cursor="hand2", padx=10, pady=20)
e1.bind("<Button-1>", lambda e: llamar(url[0]))
e1.grid(row=1, column=2)
e2 = Label(marco, text="Video 2", fg="blue", cursor="hand2", padx=10, pady=20)
e2.bind("<Button-1>", lambda e: llamar(url[1]))
e2.grid(row=2, column=2)
e3 = Label(marco, text="Video 3", fg="blue", cursor="hand2", padx=10, pady=20)
e3.bind("<Button-1>", lambda e: llamar(url[2]))
e3.grid(row=3, column=2)
e4 = Label(marco, text="Video 4", fg="blue", cursor="hand2", padx=10, pady=20)
e4.bind("<Button-1>", lambda e: llamar(url[3]))
e4.grid(row=4, column=2)
e5 = Label(marco, text="Video 5", fg="blue", cursor="hand2", padx=10, pady=20)
e5.bind("<Button-1>", lambda e: llamar(url[4]))
e5.grid(row=5, column=2)
e6 = Label(marco, text="Video 6", fg="blue", cursor="hand2", padx=10, pady=20)
e6.bind("<Button-1>", lambda e: llamar(url[5]))
e6.grid(row=6, column=2)
e7 = Label(marco, text="Video 7", fg="blue", cursor="hand2", padx=10, pady=20)
e7.bind("<Button-1>", lambda e: llamar(url[6]))
e7.grid(row=7, column=2)
e8 = Label(marco, text="Video 8", fg="blue", cursor="hand2", padx=10, pady=20)
e8.bind("<Button-1>", lambda e: llamar(url[7]))
e8.grid(row=8, column=2)
e9 = Label(marco, text="Artículo H.", fg="blue", cursor="hand2", padx=10, pady=20)
e9.bind("<Button-1>", lambda e: llamar(url[8]))
e9.grid(row=9, column=2)
e10 = Label(marco, text="Artículo C.", fg="blue", cursor="hand2", padx=10, pady=20)
e10.bind("<Button-1>", lambda e: llamar(url[9]))
e10.grid(row=10, column=2)

d1 = Entry(marco)
d1.grid(row=1, column=1, padx=10, pady=20)
d2 = Entry(marco)
d2.grid(row=2, column=1, padx=10, pady=20)
d3 = Entry(marco)
d3.grid(row=3, column=1, padx=10, pady=20)
d4 = Entry(marco)
d4.grid(row=4, column=1, padx=10, pady=20)
d5 = Entry(marco)
d5.grid(row=5, column=1, padx=10, pady=20)
d6 = Entry(marco)
d6.grid(row=6, column=1, padx=10, pady=20)
d7 = Entry(marco)
d7.grid(row=7, column=1, padx=10, pady=20)
d8 = Entry(marco)
d8.grid(row=8, column=1, padx=10, pady=20)
d9 = Entry(marco)
d9.grid(row=9, column=1, padx=10, pady=20)
d10 = Entry(marco)
d10.grid(row=10, column=1, padx=10, pady=20)

b1 = Button(marco, text="establecer enlace nº1", command=lambda: pulsar(b1, e1, d1.get()), padx=10, pady=0)
b1.grid(row=1, column=3)
b2 = Button(marco, text="establecer enlace nº2", command=lambda: pulsar(b2, e2, d2.get()), padx=10, pady=0)
b2.grid(row=2, column=3)
b3 = Button(marco, text="establecer enlace nº3", command=lambda: pulsar(b3, e3, d3.get()), padx=10, pady=0)
b3.grid(row=3, column=3)
b4 = Button(marco, text="establecer enlace nº4", command=lambda: pulsar(b4, e4, d4.get()), padx=10, pady=0)
b4.grid(row=4, column=3)
b5 = Button(marco, text="establecer enlace nº5", command=lambda: pulsar(b5, e5, d5.get()), padx=10, pady=0)
b5.grid(row=5, column=3)
b6 = Button(marco, text="establecer enlace nº6", command=lambda: pulsar(b6, e6, d6.get()), padx=10, pady=0)
b6.grid(row=6, column=3)
b7 = Button(marco, text="establecer enlace nº7", command=lambda: pulsar(b7, e7, d7.get()), padx=10, pady=0)
b7.grid(row=7, column=3)
b8 = Button(marco, text="establecer enlace nº8", command=lambda: pulsar(b8, e8, d8.get()), padx=10, pady=0)
b8.grid(row=8, column=3)
b9 = Button(marco, text="establecer enlace nº9", command=lambda: pulsar(b9, e9, d9.get()), padx=10, pady=0)
b9.grid(row=9, column=3)
b10 = Button(marco, text="establecer enlace nº10", command=lambda: pulsar(b10, e10, d10.get()), padx=10, pady=0)
b10.grid(row=10, column=3)

marco.pack()
ventana.mainloop()
